# Generated by Django 2.2.16 on 2020-10-01 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tilte',
            new_name='title',
        ),
    ]
